// <auto-generated />
namespace Orca_Zwei_The_Reckoning_Redux.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class merg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merg));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050011144_merg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
